<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TEHhub\TEHhub.csproj">
      <Private>false</Private>
      <CopyLocalSatelliteAssemblies>false</CopyLocalSatelliteAssemblies>
    </ProjectReference>
  </ItemGroup>

  <Target Name="CopyFiles" AfterTargets="Build">
    <ItemGroup>
      <_LootValueDeployFiles Include="$(OutDir)$(TargetName)$(TargetExt)" />
      <_LootValueDeployFiles Include="$(MSBuildProjectDirectory)\pathBasenameToItemName.json;$(MSBuildProjectDirectory)\uniqueArtMapping.json" />
    </ItemGroup>
    <Copy SourceFiles="@(_LootValueDeployFiles)"
          DestinationFolder="..\..\TEHhub\$(OutDir)Plugins\$(ProjectName)"
          SkipUnchangedFiles="true" />
  </Target>

</Project>
