<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>OffsetRecovery.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../TEHhub/TEHhub.csproj" />
    <ProjectReference Include="../../Plugins/myFarming/myFarming.csproj" />
    <ProjectReference Include="../../Plugins/AutoExile2/AutoExile2.csproj" />
  </ItemGroup>
</Project>
