<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <StartupObject>TEHhub.Launcher.Program</StartupObject>
    <Product>TEHhub</Product>
    <Title>TEHhub Launcher</Title>
    <Description>Launcher for the TEHhub overlay and plugin platform.</Description>
    <Authors>Tanaw; Arsenic; Gordin; GameHelper2 community contributors</Authors>
    <Version>1.8.89</Version>
    <AssemblyVersion>1.8.89.0</AssemblyVersion>
    <FileVersion>1.8.89.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AsmResolver.PE.Win32Resources" Version="6.0.1" />
  </ItemGroup>

  <Target Name="CopyFiles" AfterTargets="Build">
    <Copy SourceFiles="$(OutDir)$(TargetName).exe;$(OutDir)$(TargetName).dll;$(OutDir)$(TargetName).runtimeconfig.json;$(OutDir)AsmResolver.PE.dll;$(OutDir)AsmResolver.PE.File.dll;$(OutDir)AsmResolver.dll;$(OutDir)AsmResolver.PE.Win32Resources.dll;" DestinationFolder="..\TEHhub\$(OutDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
